services:
  db:
    image: postgres:16
    container_name: craft_db_novo
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nosdamotadb
    ports:
      - "5433:5432"